'use client';
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { operationCases, operationSettings, saveOperationSettings } from '../../lib/gateway';

type Cell = { key?: string; name?: string; label?: string; label_ko?: string; value: number | string | boolean; type?: string; choices?: string[]; min?: number; max?: number; unit?: string; editable?: boolean; text_ko?: string };
type Settings = { revision: number; limits?: Cell[]; cells?: Cell[]; history?: unknown[]; purge?: unknown };
export function OperationsSettings() {
  const [kind, setKind] = useState<'limits' | 'retention'>('limits');
  const query = useQuery({ queryKey: ['operation-settings', kind], queryFn: () => operationSettings<Settings>(kind) });
  const [changes, setChanges] = useState<Record<string, number | string | boolean>>({});
  const [reason, setReason] = useState('');
  const [feedback, setFeedback] = useState('');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const cells = query.data?.limits || query.data?.cells || [];
  return <section className="panel"><h1>운영 설정 · 보관 기간</h1><p>실제 cs 프로젝트 서버 설정을 읽고, 변경 이유와 이전 값을 기록합니다. 다른 운영자가 먼저 저장하면 다시 읽어야 합니다.</p><div className="toolbar"><button aria-pressed={kind === 'limits'} onClick={() => { setKind('limits'); setChanges({}); setFeedback(''); setError(''); }}>웹 이용 · 서비스 설정</button><button aria-pressed={kind === 'retention'} onClick={() => { setKind('retention'); setChanges({}); setFeedback(''); setError(''); }}>약관 보관 기간</button></div>{query.isPending ? <p role="status">설정 읽는 중…</p> : query.isError ? <p className="error" role="alert">{query.error.message}</p> : <form onSubmit={async e => { e.preventDefault(); setError(''); setFeedback(''); if (!reason.trim() || !Object.keys(changes).length) { setError('바꿀 값과 사유를 입력하세요.'); return; } setBusy(true); try { await saveOperationSettings(kind, { expected_revision: query.data!.revision, changes, reason }); setChanges({}); setFeedback('설정을 저장했습니다. 실제 요청 처리에 반영됩니다.'); await query.refetch(); } catch (cause) { setError(cause instanceof Error ? cause.message : '저장하지 못했습니다.'); } finally { setBusy(false); } }}><div className="toolbar"><span>현재 설정 판 {query.data?.revision}</span><button type="button" onClick={() => { setChanges({}); void query.refetch(); }}>현재 값 다시 읽기</button></div>{cells.map(cell => { const id = cell.key || cell.name!; const value = changes[id] ?? cell.value; const editable = cell.editable !== false && id !== 'retention.purge_mode'; return <label key={id} style={{ display: 'block', margin: '1rem 0' }}>{cell.label_ko || cell.label || id} {cell.unit}<small style={{ display: 'block' }}>{cell.text_ko}</small>{typeof cell.value === 'boolean' ? <select disabled={!editable} value={String(value)} onChange={e => setChanges(c => ({ ...c, [id]: e.target.value === 'true' }))}><option value="true">켜짐</option><option value="false">꺼짐</option></select> : cell.choices ? <select disabled={!editable} value={String(value)} onChange={e => setChanges(c => ({ ...c, [id]: e.target.value }))}>{cell.choices.map(choice => <option key={choice}>{choice}</option>)}</select> : <input type="number" min={cell.min} max={cell.max} disabled={!editable} value={String(value)} onChange={e => setChanges(c => ({ ...c, [id]: Number(e.target.value) }))} />}{id === 'retention.purge_mode' && <small>자료 삭제 모드는 건수 확인과 별도 승인 뒤 변경합니다.</small>}</label>; })}<label>변경 사유<input value={reason} onChange={e => setReason(e.target.value)} required maxLength={500} /></label><button type="submit" className="primary" disabled={busy}>{busy ? '저장 중…' : '설정 저장'}</button>{error && <p role="alert" className="error">{error}</p>}{feedback && <p role="status" className="success">{feedback}</p>}<details><summary>설정 변경 이력 · 정리 작업 기록</summary><pre>{JSON.stringify({ history: query.data?.history, purge: query.data?.purge }, null, 2)}</pre></details></form>}</section>;
}

type Case = { case_id: string; status: string; subject?: string; intent?: string; issue_code?: string; updated_at: string; version: number; events?: { event_id: string; event_type: string; actor_id: string; created_at: string; payload: unknown }[]; state_json?: unknown; evidence?: unknown };
export function CaseTrace({ navigate, id }: { navigate: (path: string) => void; id?: string }) {
  const query = useQuery({ queryKey: ['operation-cases', id], queryFn: () => operationCases<{ cases: Case[] } | Case>(id) });
  const data = query.data;
  return <section className="panel"><h1>{id ? '접수 처리 과정 · 근거' : '여행 접수 현황'}</h1><p>실제 접수 상태와 변경 이력을 확인합니다. 이 화면에서 접수 상태를 직접 덮어쓰지 않습니다.</p>{id && <button onClick={() => navigate('/cases')}>접수 목록으로</button>}<button onClick={() => void query.refetch()}>다시 읽기</button>{query.isPending ? <p role="status">접수 읽는 중…</p> : query.isError ? <p role="alert" className="error">{query.error.message}</p> : data && 'cases' in data ? <div style={{ overflowX: 'auto' }}><table><thead><tr><th>접수 번호</th><th>상태</th><th>요청 종류</th><th>변경 시각</th><th>조회</th></tr></thead><tbody>{data.cases.map(item => <tr key={item.case_id}><td>{item.case_id}</td><td>{item.status}</td><td>{item.intent}</td><td>{new Date(item.updated_at).toLocaleString('ko-KR')}</td><td><button onClick={() => navigate(`/cases/${item.case_id}`)}>과정 · 근거 보기</button></td></tr>)}</tbody></table>{!data.cases.length && <p>접수된 건이 없습니다.</p>}</div> : data && 'case_id' in data ? <><h2>{data.subject}</h2><p>현재 상태 {data.status} · 변경 판 {data.version}</p><ol>{data.events?.map(event => <li key={event.event_id}><strong>{event.event_type}</strong><p>{event.created_at} · {event.actor_id}</p><details><summary>이 단계의 근거 보기</summary><pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{JSON.stringify(event.payload, null, 2)}</pre></details></li>)}</ol><details><summary>현재 상태 · 근거 전체</summary><pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{JSON.stringify({ state: data.state_json, evidence: data.evidence }, null, 2)}</pre></details></> : null}</section>;
}
